### ISSUE TITLE
Will there be any update to the system?

### ISSUE THREAD

**Issue by Orphansmith** [free-beer/bh2e#17]
You can't use this anymore because any change to an actor, ability, item, etc doesn't stick.

**Comment by free-beer** [comment]
I think you need to be more specific. I've just tested on Foundry version 9, build 249 (the latest build, fresh install) and changes I make on character, spell and equipment sheets do stick. Are you on the latest version of Foundry? The move to version 9 broke a lot of things but a new version was put out to address those issues. If you aren't on the latest version then please upgrade your client and try again.

**Comment by Orphansmith** [comment]
I'm using forge-vtt which is on the latest version. It pings a compatibility issue for Black Hack (also updated to latest build). I thought it might be a problem with lag, but other games don't seem to have this issue.

Just tried it now, and nothing I change to the sheet sticks, even the dropdown options. I checked the console and saw one Uncaught type error, `Uncaught TypeError: Cannot read properties of null (reading 'querySelector') at bh2e.js:72:35`. Probably not the issue, as it occurs during setup, but it's the only console error.

Otherwise, when updating a character sheet the console outputs a `fetching the state` and `finding the state` command. I don't know much about how the system works, but I'm guessing it's trying to update the sheet, and something causes a hitch in the process. It doesn't seem to be able to save the change and then display it.

**Comment by free-beer** [comment]
Okay, just went to the expense to taking a forge license to try this out (shameless self promotion - sponsorship links on the repo root page). This works for me. I installed the system, created a world, created a character, changed things on the character - all changes stuck. Same with abilities, armour, weapons and spells.  That's leading me to think it's something specific to your set up. I'd maybe take this up with Forge if I were you.

**Comment by Orphansmith** [comment]
Will try, thanks!

**Comment by kakaroto** [comment]
> Okay, just went to the expense to taking a forge license to try this out

Hey @free-beer, I was referred to this issue and noticed the above line. Hit me up on our Discord or send us an email and we'll upgrade your account for free. The Forge gives free subscriptions to developers of Foundry VTT systems and modules, if you weren't aware, so feel free to reach out and we'll hook you up!

@Orphansmith I've checked your account on the Forge and I see that you have the bh2e system installed with version 0.2.1 which is set as compatible with 0.7.9, while the latest version of bh2e, compatible with v9, according to this repository is version 0.3.1.
You need to get it updated, and since it's a custom install (I don't see this in the official system listing, so it's not in the Bazaar), you'll need to go to the Bazaar, under 'custom systems' to keep it updated (https://forge-vtt.com/bazaar#filter=custom&type=system&sort=title).
However, I also see that the `system.json` file installed on your account has a manifest url that points to `https://raw.githubusercontent.com/free-beer/bh2e/v0.2.2/system.json` which is pointing to a specific release and will never be able to find updates for you. That would explain your issues.

I recommend you re-install it again directly from the manifest URL, which will update it and will also allow it to find future updates as the new manifest contains a proper latest-pointing url : https://raw.githubusercontent.com/free-beer/bh2e/master/system.json

**Comment by Orphansmith** [comment]
That worked, thanks!
