### ISSUE TITLE
Large weapon Attribute Roll correction

### ISSUE THREAD

**Issue by theblackveil** [free-beer/bh2e#3]
Good morning!

I noticed that weapons set to Large size are not correctly adding +1d4 to Attribute rolls for Attacking/Defending. Instead, it is only adding 1d4 to the damage.

I've found, in chat_messages.js, where the damage reference for adding that 1d4 is, but I'm not familiar enough with json, JavaScript, HTML, etc. to figure out where I need to adjust the actual rolls.

Is this something you are able to address? If not, could you direct me to the place(s) where roll parameters are defined for Large size weapons so I can hopefully piece it together?

Thank you for all your work with this.

**Comment by free-beer** [comment]
Thanks for the report. You were in the right area of the code for where the change needs to be made. I'll make it though because, while I was looking at it, I spotted another issue (it can incorrectly determine if an attack roll is a critical for rolls with advantage or disadvantage). I'll try and get to this shortly.

**Comment by free-beer** [comment]
After checking the critical thing isn't an issue after all. I've applied a change that addresses the issue with large weapon attack rolls and released version 0.2.3. Going to close this now but if you spot another issue then let me know.
